export const experiences = [
  {
    role: "Associate Team Lead SRE",
    company: "GTN",
    duration: "April 2026 - Present",
    location: "Colombo, Sri Lanka",
    responsibilities: [
      "Promoted to Associate Team Lead, guiding feed ops SRE strategy across EC2, MSK/Kafka, Solr, Redis, EFS, and S3 in 4 AWS regions.",
      "Mentor SREs, reviewing infrastructure changes and CI/CD designs before production rollout.",
      "Own on-call escalation strategy and lead incident response for critical feed infrastructure outages.",
      "Drive architecture decisions for Kafka, Solr, and Redis clusters across reliability, cost, and performance.",
      "Translate infrastructure roadmap priorities into sprint goals with engineering leadership and capacity planning.",
    ],
    technologies: ["AWS", "Kafka", "Solr", "Redis", "EFS", "S3", "CI/CD"],
    achievements: [
      "Leading SRE strategy across 4 AWS regions",
      "Mentoring the SRE team",
      "Owns critical incident escalation strategy",
    ],
  },
  {
    role: "Senior Site Reliability Engineer",
    company: "GTN",
    duration: "April 2024 - April 2026",
    location: "Colombo, Sri Lanka",
    responsibilities: [
      "Reduced deployment times by 40% by architecting and optimizing GitLab CI/CD pipelines with automated testing and deployment.",
      "Increased system uptime by implementing Datadog for critical systems monitoring and systematized incident response.",
      "Optimized cloud costs by 25% through initiatives managing resources across AWS accounts without sacrificing availability.",
      "Designed and managed AWS infrastructure across 2 regions with disaster recovery plans ensuring 99.9% uptime.",
      "Led incident response drills improving system recovery time across critical platforms.",
      "Collaborated with development teams to optimize application performance, reducing latency consistently.",
      "Trained junior SREs on best practices and incident management, enhancing team response efficiency.",
    ],
    technologies: ["AWS", "GitLab", "Datadog", "Terraform", "Kubernetes"],
    achievements: [
      "Reduced deployment time by 40%",
      "Optimized cloud costs by 25%",
      "Ensured 99.9% uptime across 2 AWS regions",
    ],
  },
  {
    role: "Site Reliability Engineer",
    company: "GTN",
    duration: "April 2021 - April 2024",
    location: "Colombo, Sri Lanka",
    responsibilities: [
      "Supported AWS migration for 100+ servers across regions, reducing latency by 30% through optimized EC2, RDS, and VPC setups.",
      "Established infrastructure as code frameworks with Terraform, Packer, and Ansible, enabling consistent, repeatable, and scalable deployments across environments.",
      "Maximized software release speed by 40% by optimizing GitLab CI/CD pipelines for Java and C++ projects.",
      "Lowered critical incident recurrence by 30% by implementing Datadog monitoring solutions with custom alerts and dashboards.",
      "Recognized issues and conducted root cause analysis of critical production incidents and applied preventive controls, reducing recurrence and strengthening system stability.",
    ],
    technologies: ["AWS", "Terraform", "Packer", "Ansible", "GitLab", "Datadog", "Java"],
    achievements: [
      "Supported migration of 100+ servers",
      "Maximized release speed by 40%",
      "Lowered incident recurrence by 30%",
    ],
  },
  {
    role: "Network Engineering Intern",
    company: "N-Able (Pvt) Ltd",
    duration: "June 2019 - December 2019",
    location: "Colombo, Sri Lanka",
    responsibilities: [
      "Fine-tuned network performance, increasing connectivity speed by 40%, resulting in enhanced scalability for the Metro Ethernet project.",
      "Enhanced base station functionality within the Self-Organizing Network (SON) project, enabling more efficient network operations.",
      "Enhanced self-optimization, configuration, and healing for reliable network performance.",
    ],
    technologies: ["Ethernet", "SON", "Network Optimization"],
    achievements: [
      "Increased connectivity speed by 40%",
      "Enhanced SON base station functionality",
    ],
  },
];
